theme: jekyll-theme-minimal
title: Are the films from hollywood and bollywood really that different ?
description: Exploration of the factors that lead a film produced in Hollywood or Bollywood to have a greate rating on IMDb
show_downloads: True
navigation:
  - title: Home
    url: page_1
